CREATE TABLE UBICACIONES
(
COD_UBICACION INT(3) AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL CHECK (NOMBRE = UPPER(NOMBRE)),
PAIS VARCHAR(20) NOT NULL CHECK (PAIS = UPPER(PAIS))
);

CREATE TABLE ALOJAMIENTOS
(
COD_ALOJAMIENTO INT(6) AUTO_INCREMENT PRIMARY KEY,
COD_UBICACION INT(3),
NOMBRE VARCHAR(20) NOT NULL CHECK (NOMBRE = UPPER(NOMBRE)),
DESCRIPCION VARCHAR(200),
LONGITUD FLOAT(6),
LATITUD FLOAT(6),
TIPO CHAR NOT NULL CHECK (TIPO IN('H', 'C', 'A')),
ESTRELLAS INT(1) CHECK (ESTRELLAS BETWEEN 1 AND 5),
ALTURA INT(2),
TARIFA_NORMAL FLOAT(6) NOT NULL,
TARIFA_VERANO FLOAT(6),
REGARGO FLOAT(6) DEFAULT 0,
DESAYUNO FLOAT(6) DEFAULT 0,
MEDIA_PENSION FLOAT(6) DEFAULT 0,
PENSION_COMPLETA FLOAT(6) DEFAULT 0,
FOREIGN KEY (COD_UBICACION) REFERENCES UBICACIONES (COD_UBICACION) ON DELETE CASCADE
);

CREATE TABLE CLIENTES
(
COD_CLIENTE INT(6) AUTO_INCREMENT PRIMARY KEY,
DNI VARCHAR(9) UNIQUE NOT NULL CHECK (DNI = UPPER(DNI)),
CONTRASENA VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(20),
APELLIDOS VARCHAR(20),
FECHANAC DATE,
EMAIL VARCHAR(30)
);

CREATE TABLE DORMITORIOS
(
COD_DORMITORIO INT(6) AUTO_INCREMENT PRIMARY KEY,
CTD_CAMAS_SIMPLES INT(3),
CTD_CAMAS_MATRIMONIO INT(2),
CTD_CAMAS_INFANTIL INT(2),
TAMANO FLOAT(4) NOT NULL
);

CREATE TABLE RESERVAS
(
COD_RESERVA INT(6) AUTO_INCREMENT PRIMARY KEY,
COD_CLIENTE INT(6),
COD_ALOJAMIENTO INT(6),
FECHACOMPRA DATETIME NOT NULL,
FECHAENTRADA DATE NOT NULL,
FECHASALIDA DATE NOT NULL,
PRECIOTOTAL FLOAT(6) NOT NULL,
FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES (COD_CLIENTE) ON DELETE CASCADE,
FOREIGN KEY (COD_ALOJAMIENTO) REFERENCES ALOJAMIENTOS (COD_ALOJAMIENTO) ON DELETE CASCADE
);

CREATE TABLE ALOJAMIENTO_DORMITORIO
(
COD_ALOJAMIENTO INT(6),
COD_DORMITORIO INT(6),
CANTIDAD INT(3) NOT NULL,
FOREIGN KEY (COD_ALOJAMIENTO) REFERENCES ALOJAMIENTOS (COD_ALOJAMIENTO) ON DELETE CASCADE,
FOREIGN KEY (COD_DORMITORIO) REFERENCES DORMITORIOS (COD_DORMITORIO) ON DELETE CASCADE
);

CREATE TABLE RESERVA_DORMITORIO
(
COD_RESERVA INT(6),
COD_DORMITORIO INT(6),
CANTIDAD INT(3) NOT NULL,
FOREIGN KEY (COD_RESERVA) REFERENCES RESERVAS (COD_RESERVA) ON DELETE CASCADE,
FOREIGN KEY (COD_DORMITORIO) REFERENCES DORMITORIOS (COD_DORMITORIO) ON DELETE CASCADE
);
